<!--

    Copyright © 2016-2024 The Thingsboard Authors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.thingsboard</groupId>
        <version>3.9.0-SNAPSHOT</version>
        <artifactId>common</artifactId>
    </parent>
    <groupId>org.thingsboard.common</groupId>
    <artifactId>edge-api</artifactId>
    <packaging>jar</packaging>

    <name>Thingsboard Server Remote Edge wrapper</name>
    <url>https://thingsboard.io</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <main.dir>${basedir}/../..</main.dir>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.thingsboard.common</groupId>
            <artifactId>data</artifactId>
        </dependency>
        <dependency>
            <groupId>org.thingsboard.common</groupId>
            <artifactId>queue</artifactId>
        </dependency>
        <dependency>
            <groupId>com.diffblue.cover</groupId>
            <artifactId>cover-annotations</artifactId>
            <version>1.9.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.thingsboard.common</groupId>
            <artifactId>message</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <version>3.2.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                <excludes>
                    <exclude>org/thingsboard/edge/rpc/EdgeGrpcClient$1.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AdminSettingsUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AdminSettingsUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AlarmCommentUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AlarmCommentUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AlarmUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AlarmUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AssetProfileUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AssetProfileUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AssetUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AssetUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AttributeDeleteMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AttributeDeleteMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AttributesRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/AttributesRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ConnectRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ConnectRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ConnectResponseCode.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ConnectResponseMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ConnectResponseMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/CustomerUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/CustomerUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DashboardUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DashboardUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceCredentialsRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceCredentialsRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceCredentialsUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceCredentialsUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceProfileDevicesRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceProfileDevicesRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceProfileUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceProfileUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceRpcCallMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceRpcCallMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DeviceUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DownlinkMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DownlinkMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DownlinkResponseMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/DownlinkResponseMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeConfiguration.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeConfiguration$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeEntityType.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeProtos.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$1.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$2.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$3.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$AsyncService.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$EdgeRpcServiceBaseDescriptorSupplier.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$EdgeRpcServiceBlockingStub.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$EdgeRpcServiceFileDescriptorSupplier.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$EdgeRpcServiceFutureStub.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$EdgeRpcServiceImplBase.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$EdgeRpcServiceMethodDescriptorSupplier.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$EdgeRpcServiceStub.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeRpcServiceGrpc$MethodHandlers.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EdgeVersion.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EntityDataProto.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EntityDataProto$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EntityViewUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EntityViewUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EntityViewsRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/EntityViewsRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NodeConnectionInfoProto.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NodeConnectionInfoProto$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NotificationRuleUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NotificationRuleUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NotificationTargetUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NotificationTargetUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NotificationTemplateUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/NotificationTemplateUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/OAuth2ClientUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/OAuth2ClientUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/OAuth2DomainUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/OAuth2DomainUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/OtaPackageUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/OtaPackageUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ProcessingStrategyProto.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ProcessingStrategyProto$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/QueueUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/QueueUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RelationRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RelationRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RelationUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RelationUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RequestMsgType.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ResourceUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ResourceUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ResponseMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/ResponseMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RpcRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RpcRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RpcResponseMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RpcResponseMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainConnectionInfoProto.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainConnectionInfoProto$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainMetadataRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainMetadataRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainMetadataUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainMetadataUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleChainUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleNodeProto.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/RuleNodeProto$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/SubmitStrategyProto.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/SubmitStrategyProto$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/SyncCompletedMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/SyncCompletedMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/SyncRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/SyncRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/TenantProfileUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/TenantProfileUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/TenantUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/TenantUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UpdateMsgType.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UplinkMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UplinkMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UplinkResponseMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UplinkResponseMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UserCredentialsRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UserCredentialsRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UserCredentialsUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UserCredentialsUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UserUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/UserUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/WidgetBundleTypesRequestMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/WidgetBundleTypesRequestMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/WidgetTypeUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/WidgetTypeUpdateMsg$Builder.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/WidgetsBundleUpdateMsg.class</exclude>
                    <exclude>org/thingsboard/server/gen/edge/v1/WidgetsBundleUpdateMsg$Builder.class</exclude>
                </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>thingsboard-repo-deploy</id>
            <name>ThingsBoard Repo Deployment</name>
            <url>https://repo.thingsboard.io/artifactory/libs-release-public</url>
        </repository>
    </distributionManagement>

</project>
