<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.thingsboard</groupId>
        <version>3.9.0-SNAPSHOT</version>
        <artifactId>thingsboard</artifactId>
    </parent>
    <artifactId>mutation-aggregation-module</artifactId>
    <version>3.9.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Thingsboard Mutation Aggregation</name>
    <url>https://thingsboard.io</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <main.dir>${basedir}/..</main.dir>
    </properties>

  <dependencies>
    <dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>application</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>actor</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>cache</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>cluster-api</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>coap-server</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>dao-api</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>data</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>edge-api</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>message</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <!--<dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>proto</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>queue</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common.script</groupId>
      <artifactId>script-api</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common.script</groupId>
      <artifactId>remote-js-client</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>stats</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <!--<dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>transport</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <dependency>
      <groupId>org.thingsboard.common.transport</groupId>
      <artifactId>coap</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common.transport</groupId>
      <artifactId>http</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common.transport</groupId>
      <artifactId>lwm2m</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common.transport</groupId>
      <artifactId>mqtt</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common.transport</groupId>
      <artifactId>snmp</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>util</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.common</groupId>
      <artifactId>version-control</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>dao</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>monitoring</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <!--<dependency>
      <groupId>org.thingsboard.msa</groupId>
      <artifactId>js-executor</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa</groupId>
      <artifactId>monitoring</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa</groupId>
      <artifactId>tb</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa</groupId>
      <artifactId>tb-node</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa.transport</groupId>
      <artifactId>coap</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa.transport</groupId>
      <artifactId>http</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa.transport</groupId>
      <artifactId>lwm2m</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa.transport</groupId>
      <artifactId>mqtt</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa.transport</groupId>
      <artifactId>snmp</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <dependency>
      <groupId>org.thingsboard.msa</groupId>
      <artifactId>vc-executor</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <!--<dependency>
      <groupId>org.thingsboard.msa.transport</groupId>
      <artifactId>vc-executor-docker</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <!--<dependency>
      <groupId>org.thingsboard.msa.transport</groupId>
      <artifactId>web-ui</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
    <dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>netty-mqtt</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>rest-client</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.rule-engine</groupId>
      <artifactId>rule-engine-api</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.rule-engine</groupId>
      <artifactId>rule-engine-components</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>tools</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.transport</groupId>
      <artifactId>coap</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.transport</groupId>
      <artifactId>http</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.transport</groupId>
      <artifactId>lwm2m</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.transport</groupId>
      <artifactId>mqtt</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.thingsboard.transport</groupId>
      <artifactId>snmp</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>
    <!--<dependency>
      <groupId>org.thingsboard</groupId>
      <artifactId>ui-ngx</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
	    <!--<dependency>
      <groupId>org.thingsboard.msa</groupId>
      <artifactId>ui-ngx</artifactId>
      <version>3.9.0-SNAPSHOT</version>
    </dependency>-->
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
		<version>1.17.1</version>
        <executions>
          <execution>
            <id>run-mutation-tests</id>
            <phase>none</phase>
          </execution>
          <execution>
            <id>report</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>report-aggregate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>